#!/usr/bin/env python3
"""Walk vault, regenerate index.md from frontmatter titles + folder layout."""

from __future__ import annotations

import re
from collections import defaultdict
from datetime import date
from pathlib import Path

VAULT = Path(__file__).resolve().parent.parent.parent
INDEX_PATH = VAULT / "index.md"
IGNORED_DIRS = {"raw", ".obsidian", ".git", ".claude"}
IGNORED_FILES = {"index.md", "CLAUDE.md"}


def parse_frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}
    data: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        data[key.strip()] = value.strip().strip('"').strip("'")
    return data


def iter_notes() -> list[Path]:
    notes: list[Path] = []
    for path in VAULT.rglob("*.md"):
        rel = path.relative_to(VAULT)
        if rel.parts[0] in IGNORED_DIRS:
            continue
        if rel.name in IGNORED_FILES and len(rel.parts) == 1:
            continue
        notes.append(path)
    return notes


def folder_key(rel: Path) -> str:
    parts = rel.parts[:-1]
    return "/".join(parts) if parts else "(root)"


def link_for(rel: Path) -> str:
    stem = rel.with_suffix("").as_posix()
    name = rel.stem
    return f"[[{stem}|{name}]]"


def summarize(data: dict[str, str], body_first_line: str) -> str:
    summary = data.get("description") or body_first_line or ""
    summary = summary.strip().lstrip("#").strip()
    if len(summary) > 120:
        summary = summary[:117] + "..."
    return summary


def first_body_line(text: str) -> str:
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            text = text[end + 5 :]
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            return stripped
    return ""


def main() -> int:
    notes = iter_notes()
    grouped: dict[str, list[tuple[Path, dict[str, str], str]]] = defaultdict(list)

    for path in notes:
        text = path.read_text(encoding="utf-8")
        data = parse_frontmatter(text)
        summary = summarize(data, first_body_line(text))
        rel = path.relative_to(VAULT)
        grouped[folder_key(rel)].append((rel, data, summary))

    today = date.today().isoformat()
    lines: list[str] = [
        "---",
        'title: "Vault Index"',
        f"updated: {today}",
        "---",
        "",
        "# Index",
        "",
        "_Auto-generated by `scripts/reindex.py`. Do not hand-edit._",
        "",
    ]

    if not grouped:
        lines.append("Vault empty.")
    else:
        for folder in sorted(grouped):
            lines.append(f"## {folder}")
            lines.append("")
            lines.append("| Page | Type | Summary |")
            lines.append("|------|------|---------|")
            for rel, data, summary in sorted(grouped[folder], key=lambda x: x[0].as_posix()):
                title = data.get("title", rel.stem)
                ntype = data.get("type", "")
                lines.append(f"| {link_for(rel)} | {ntype} | {summary} |")
            lines.append("")

    INDEX_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {INDEX_PATH.relative_to(VAULT)} — {len(notes)} notes across {len(grouped)} folders.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
